# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

import os
import sys
import time

from os.path import join
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QMainWindow, QApplication
from PyQt5.QtWidgets import QFileDialog, QMessageBox

from ExcelToWord_109 import ExcelToWord_doc, ExcelToWord_first
from ExcelToWord_109 import ExcelToWord_second

class Ui_Test(object):
    def setupUi(self, Test):
        Test.setObjectName("Test")
        Test.resize(834, 473)
        self.verticalLayout = QtWidgets.QVBoxLayout(Test)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Test)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Tab = QtWidgets.QWidget()
        self.Tab.setObjectName("Tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_21 = QtWidgets.QLabel(self.Tab)
        self.label_21.setMinimumSize(QtCore.QSize(70, 0))
        self.label_21.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_12.addWidget(self.label_21)
        self.first_in = QtWidgets.QLineEdit(self.Tab)
        self.first_in.setObjectName("first_in")
        self.horizontalLayout_12.addWidget(self.first_in)
        self.label_22 = QtWidgets.QLabel(self.Tab)
        self.label_22.setMinimumSize(QtCore.QSize(50, 0))
        self.label_22.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_12.addWidget(self.label_22)
        self.sheet_in = QtWidgets.QLineEdit(self.Tab)
        self.sheet_in.setMinimumSize(QtCore.QSize(120, 0))
        self.sheet_in.setMaximumSize(QtCore.QSize(120, 16777215))
        self.sheet_in.setObjectName("sheet_in")
        self.horizontalLayout_12.addWidget(self.sheet_in)
        self.btn_excel = QtWidgets.QPushButton(self.Tab)
        self.btn_excel.setObjectName("btn_excel")
        self.horizontalLayout_12.addWidget(self.btn_excel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.Tab)
        self.label_23.setMinimumSize(QtCore.QSize(70, 0))
        self.label_23.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.word_in = QtWidgets.QLineEdit(self.Tab)
        self.word_in.setObjectName("word_in")
        self.horizontalLayout_13.addWidget(self.word_in)
        self.btn_word = QtWidgets.QPushButton(self.Tab)
        self.btn_word.setObjectName("btn_word")
        self.horizontalLayout_13.addWidget(self.btn_word)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_24 = QtWidgets.QLabel(self.Tab)
        self.label_24.setMinimumSize(QtCore.QSize(70, 0))
        self.label_24.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_14.addWidget(self.label_24)
        self.company_in = QtWidgets.QLineEdit(self.Tab)
        self.company_in.setMinimumSize(QtCore.QSize(100, 0))
        self.company_in.setObjectName("company_in")
        self.horizontalLayout_14.addWidget(self.company_in)
        self.label_25 = QtWidgets.QLabel(self.Tab)
        self.label_25.setMinimumSize(QtCore.QSize(70, 0))
        self.label_25.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_14.addWidget(self.label_25)
        self.cover_date_in = QtWidgets.QDateEdit(self.Tab)
        self.cover_date_in.setMinimumSize(QtCore.QSize(110, 0))
        self.cover_date_in.setMaximumSize(QtCore.QSize(110, 16777215))
        self.cover_date_in.setAccelerated(False)
        self.cover_date_in.setProperty("showGroupSeparator", False)
        self.cover_date_in.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 10, 10), QtCore.QTime(0, 0, 0)))
        self.cover_date_in.setCalendarPopup(True)
        self.cover_date_in.setObjectName("cover_date_in")
        self.horizontalLayout_14.addWidget(self.cover_date_in)
        self.label_26 = QtWidgets.QLabel(self.Tab)
        self.label_26.setMinimumSize(QtCore.QSize(70, 0))
        self.label_26.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_14.addWidget(self.label_26)
        self.consultant_in = QtWidgets.QLineEdit(self.Tab)
        self.consultant_in.setMinimumSize(QtCore.QSize(100, 0))
        self.consultant_in.setObjectName("consultant_in")
        self.horizontalLayout_14.addWidget(self.consultant_in)
        self.label_27 = QtWidgets.QLabel(self.Tab)
        self.label_27.setMinimumSize(QtCore.QSize(70, 0))
        self.label_27.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_14.addWidget(self.label_27)
        self.first_date_in = QtWidgets.QDateEdit(self.Tab)
        self.first_date_in.setMinimumSize(QtCore.QSize(110, 0))
        self.first_date_in.setMaximumSize(QtCore.QSize(110, 16777215))
        self.first_date_in.setCalendarPopup(True)
        self.first_date_in.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.first_date_in.setObjectName("first_date_in")
        self.horizontalLayout_14.addWidget(self.first_date_in)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_19 = QtWidgets.QLabel(self.Tab)
        self.label_19.setMinimumSize(QtCore.QSize(70, 0))
        self.label_19.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_11.addWidget(self.label_19)
        self.tool_name_in = QtWidgets.QLineEdit(self.Tab)
        self.tool_name_in.setObjectName("tool_name_in")
        self.horizontalLayout_11.addWidget(self.tool_name_in)
        self.label_20 = QtWidgets.QLabel(self.Tab)
        self.label_20.setMinimumSize(QtCore.QSize(70, 0))
        self.label_20.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        self.tool_version_in = QtWidgets.QLineEdit(self.Tab)
        self.tool_version_in.setObjectName("tool_version_in")
        self.horizontalLayout_11.addWidget(self.tool_version_in)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.textEdit = QtWidgets.QTextEdit(self.Tab)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.Tab)
        self.label_4.setMinimumSize(QtCore.QSize(70, 0))
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.save_in = QtWidgets.QLineEdit(self.Tab)
        self.save_in.setObjectName("save_in")
        self.horizontalLayout_4.addWidget(self.save_in)
        self.btn_save = QtWidgets.QPushButton(self.Tab)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_4.addWidget(self.btn_save)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.btn_clear = QtWidgets.QPushButton(self.Tab)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_15.addWidget(self.btn_clear)
        self.btn_run = QtWidgets.QPushButton(self.Tab)
        self.btn_run.setObjectName("btn_run")
        self.horizontalLayout_15.addWidget(self.btn_run)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.tabWidget.addTab(self.Tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.label_0 = QtWidgets.QLabel(self.tab)
        self.label_0.setMinimumSize(QtCore.QSize(70, 0))
        self.label_0.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_0.setObjectName("label_0")
        self.horizontalLayout_1.addWidget(self.label_0)
        self.first_in_2 = QtWidgets.QLineEdit(self.tab)
        self.first_in_2.setObjectName("first_in_2")
        self.horizontalLayout_1.addWidget(self.first_in_2)
        self.label_1 = QtWidgets.QLabel(self.tab)
        self.label_1.setMinimumSize(QtCore.QSize(50, 0))
        self.label_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_1.addWidget(self.label_1)
        self.sheet_in_2 = QtWidgets.QLineEdit(self.tab)
        self.sheet_in_2.setMinimumSize(QtCore.QSize(120, 0))
        self.sheet_in_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.sheet_in_2.setObjectName("sheet_in_2")
        self.horizontalLayout_1.addWidget(self.sheet_in_2)
        self.btn_excel_2 = QtWidgets.QPushButton(self.tab)
        self.btn_excel_2.setObjectName("btn_excel_2")
        self.horizontalLayout_1.addWidget(self.btn_excel_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.second_in = QtWidgets.QLineEdit(self.tab)
        self.second_in.setObjectName("second_in")
        self.horizontalLayout.addWidget(self.second_in)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setMinimumSize(QtCore.QSize(50, 0))
        self.label_9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.sheet_in_3 = QtWidgets.QLineEdit(self.tab)
        self.sheet_in_3.setMinimumSize(QtCore.QSize(120, 0))
        self.sheet_in_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.sheet_in_3.setObjectName("sheet_in_3")
        self.horizontalLayout.addWidget(self.sheet_in_3)
        self.btn_excel_3 = QtWidgets.QPushButton(self.tab)
        self.btn_excel_3.setObjectName("btn_excel_3")
        self.horizontalLayout.addWidget(self.btn_excel_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setMinimumSize(QtCore.QSize(70, 0))
        self.label_30.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_16.addWidget(self.label_30)
        self.consultant_in_2 = QtWidgets.QLineEdit(self.tab)
        self.consultant_in_2.setObjectName("consultant_in_2")
        self.horizontalLayout_16.addWidget(self.consultant_in_2)
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setMinimumSize(QtCore.QSize(70, 0))
        self.label_31.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_16.addWidget(self.label_31)
        self.second_date_in = QtWidgets.QDateEdit(self.tab)
        self.second_date_in.setMinimumSize(QtCore.QSize(110, 0))
        self.second_date_in.setMaximumSize(QtCore.QSize(110, 16777215))
        self.second_date_in.setCalendarPopup(True)
        self.second_date_in.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.second_date_in.setObjectName("second_date_in")
        self.horizontalLayout_16.addWidget(self.second_date_in)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMinimumSize(QtCore.QSize(110, 0))
        self.label_3.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.save_in_2 = QtWidgets.QLineEdit(self.tab)
        self.save_in_2.setObjectName("save_in_2")
        self.horizontalLayout_3.addWidget(self.save_in_2)
        self.btn_save_2 = QtWidgets.QPushButton(self.tab)
        self.btn_save_2.setObjectName("btn_save_2")
        self.horizontalLayout_3.addWidget(self.btn_save_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btn_clear_2 = QtWidgets.QPushButton(self.tab)
        self.btn_clear_2.setObjectName("btn_clear_2")
        self.horizontalLayout_5.addWidget(self.btn_clear_2)
        self.btn_run_2 = QtWidgets.QPushButton(self.tab)
        self.btn_run_2.setObjectName("btn_run_2")
        self.horizontalLayout_5.addWidget(self.btn_run_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.clickedconnect()
        self.retranslateUi(Test)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Test)

    def retranslateUi(self, Test):
        _translate = QtCore.QCoreApplication.translate
        Test.setWindowTitle(_translate("Test", "Test"))
        self.label_21.setText(_translate("Test", "初掃 Excel :"))
        self.label_22.setText(_translate("Test", "分頁"))
        self.btn_excel.setText(_translate("Test", "瀏覽"))
        self.label_23.setText(_translate("Test", "模板 Word :"))
        self.btn_word.setText(_translate("Test", "瀏覽"))
        self.label_24.setText(_translate("Test", "公司名稱"))
        self.label_25.setText(_translate("Test", "產出日期"))
        self.label_26.setText(_translate("Test", "檢測顧問"))
        self.label_27.setText(_translate("Test", "檢測日期"))
        self.label_19.setText(_translate("Test", "工具名稱"))
        self.label_20.setText(_translate("Test", "工具版本"))
        self.textEdit.setHtml(_translate("Test", "初始化成功..."))
        self.label_4.setText(_translate("Test", "儲存資料夾"))
        self.btn_save.setText(_translate("Test", "瀏覽"))
        self.btn_clear.setText(_translate("Test", "清除"))
        self.btn_run.setText(_translate("Test", "執行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab), _translate("Test", "初掃"))
        self.label_0.setText(_translate("Test", "初掃 Excel :"))
        self.label_1.setText(_translate("Test", "分頁"))
        self.label.setText(_translate("Test", "複掃 Excel :"))
        self.label_9.setText(_translate("Test", "分頁"))
        self.btn_excel_2.setText(_translate("Test", "瀏覽"))
        self.btn_excel_3.setText(_translate("Test", "瀏覽"))
        self.label_30.setText(_translate("Test", "檢測顧問 :"))
        self.label_31.setText(_translate("Test", "檢測日期"))
        self.textEdit_2.setHtml(_translate("Test", "初始化成功...."))
        self.label_3.setText(_translate("Test", "初掃儲存資料夾 :"))
        self.btn_save_2.setText(_translate("Test", "選擇資料夾"))
        self.btn_clear_2.setText(_translate("Test", "清除"))
        self.btn_run_2.setText(_translate("Test", "執行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Test", "複掃"))

    def clickedconnect(self):      
        self.btn_word.clicked.connect(self.open_file)
        self.btn_excel.clicked.connect(self.open_excel_1)
        self.btn_save.clicked.connect(self.save_path_1)
        self.btn_run.clicked.connect(self.first_run)

        self.btn_excel_2.clicked.connect(self.open_excel_1)
        self.btn_excel_3.clicked.connect(self.open_excel_2)
        self.btn_save_2.clicked.connect(self.save_path_2)
        self.btn_run_2.clicked.connect(self.second_run)

        self.set_clear(self.btn_clear)
        self.set_clear(self.btn_clear_2)

    def set_clear(self, obj):
        if obj is self.btn_clear:
            obj.clicked.connect(self.first_in.clear)
            obj.clicked.connect(self.sheet_in.clear)
            obj.clicked.connect(self.word_in.clear)
            obj.clicked.connect(self.company_in.clear)
            obj.clicked.connect(self.consultant_in.clear)
            obj.clicked.connect(self.tool_name_in.clear)
            obj.clicked.connect(self.tool_version_in.clear)
            obj.clicked.connect(self.textEdit.clear)
            obj.clicked.connect(self.save_in.clear)
            QApplication.processEvents()
        elif obj is self.btn_clear_2:
            obj.clicked.connect(self.second_in.clear)
            obj.clicked.connect(self.save_in_2.clear)
            obj.clicked.connect(self.consultant_in_2.clear)
            obj.clicked.connect(self.textEdit_2.clear)
            obj.clicked.connect(self.save_in_2.clear)
            QApplication.processEvents()

    def open_excel_1(self):
        file_name, _ = QFileDialog.getOpenFileName(self, "選取檔案", "./", "All Files (*)")
        self.first_in.setText(file_name)
        self.first_in_2.setText(file_name)

    def open_excel_2(self):
        file_name, _ = QFileDialog.getOpenFileName(self, "選取檔案", "./", "All Files (*)")
        self.second_in.setText(file_name)

    def open_file(self):
        file_name, _ = QFileDialog.getOpenFileName(self, "選取檔案", "./", "All Files (*)")
        self.word_in.setText(file_name)

    def save_path_1(self):
        directory = QFileDialog.getExistingDirectory(self, "選取資料夾", "./")
        self.save_in.setText(directory)
    
    def save_path_2(self):
        directory = QFileDialog.getExistingDirectory(self, "選取資料夾", "./")
        self.save_in_2.setText(directory)

    def first_run(self):
        word = self.word_in.text()
        company = self.company_in.text()
        cover_date = self.cover_date_in.text().split('/', 1)[1]
        tool_name = self.tool_name_in.text()
        tool_version = self.tool_version_in.text()

        excel = self.first_in.text()
        sheet = self.sheet_in.text()
        consultant = self.consultant_in.text()
        first_date = self.first_date_in.text().split('/', 1)[1]
        save = self.save_in.text()

        if not word or not company or not cover_date or not tool_name or not tool_version:
            QMessageBox.warning(self, "缺少資料", "請確認必要資料是否填入", QMessageBox.Ok)

        elif not excel or not sheet or not consultant or not first_date or not save:
            QMessageBox.warning(self, "缺少資料", "請確認必要資料是否填入", QMessageBox.Ok)

        else:
            all_text = []
            all_text.append("\nExcel Path : %s" % excel)
            all_text.append("Sheet : %s" % sheet)
            all_text.append("Word Path : %s" % word)
            all_text.append("Company : %s" % company)
            all_text.append("Cover Date : %s First Date : %s" % (cover_date, first_date))
            all_text.append("Tool name : %s \nTool version : %s" % (tool_name, tool_version))
            all_text.append("Save file Path : %s" % save)
            all_text.append("執行中...")
            all_text.append('\n')
            for text in all_text:
                self.textEdit.append(text)
                QApplication.processEvents()

            ExcelToWord_doc(word, company, cover_date, tool_name, tool_version)
            ExcelToWord_first('tmp_template.docx', excel, sheet, save, first_date, consultant)

            self.textEdit.append("執行完畢!!")
            self.textEdit.moveCursor(QtGui.QTextCursor.End)
            QApplication.processEvents()

    def second_run(self):
        excel = self.first_in_2.text()
        sheet = self.sheet_in_2.text()
        
        excel2 = self.second_in.text()
        sheet2 = self.sheet_in_3.text()
        consultant2 = self.consultant_in_2.text()
        second_date = self.second_date_in.text().split('/', 1)[1]
        save = self.save_in_2.text()

        if not excel or not sheet or not excel2 or not sheet2 or not consultant2 or not second_date or not save:
            QMessageBox.warning(self, "缺少資料", "請確認必要資料是否填入", QMessageBox.Ok)
        else:
            all_text = []
            all_text.append("\nExcel Path : %s" % excel)
            all_text.append("Sheet : %s" % sheet)
            all_text.append("Second Date : %s" % second_date)
            all_text.append("Consultant : %s" % consultant2)
            all_text.append("Save file Path : %s" % save)
            all_text.append("執行中...")
            all_text.append('\n')
            for text in all_text:
                self.textEdit_2.append(text)
                QApplication.processEvents()

            for f in os.listdir(save):
                f_path = join(save, f)
                ExcelToWord_second(f_path, excel, excel2, sheet, sheet2, second_date, consultant2)

            self.textEdit_2.append("執行完畢!!")
            self.textEdit_2.moveCursor(QtGui.QTextCursor.End)
            QApplication.processEvents()

class MainWindow(QMainWindow, Ui_Test):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        central_widget = QWidget()
        self.setCentralWidget(central_widget) # new central widget    
        self.setupUi(central_widget)
        
if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())